/**
 * Buku Foto Makanan GEMAS
 * Data makanan beserta ukuran rumah tangga dan kandungan gizi.
 *
 * Sumber kandungan gizi:
 *  - DKBM (Daftar Komposisi Bahan Makanan) - Kemenkes RI
 *  - Persatuan Ahli Gizi Indonesia (PERSAGI)
 *  - Aplikasi Buku Pintar Gizi (Kemenkes)
 *
 * Catatan: Nilai energi/protein/lemak/karbohidrat per porsi (per URT).
 * Beberapa nilai adalah perkiraan berdasarkan rata-rata komposisi bahan.
 * Admin dapat memperbarui data ini sesuai kebutuhan.
 */

export type FoodCategory =
  | "makanan-pokok"
  | "lauk-hewani"
  | "lauk-nabati"
  | "sayuran"
  | "buah"
  | "minyak-lemak"
  | "camilan";

export interface FoodItem {
  id: string;
  nama: string;
  kategori: FoodCategory;
  urt: string; // ukuran rumah tangga
  beratGram: number;
  energiKkal: number;
  proteinG: number;
  lemakG: number;
  karbohidratG: number;
  /** emoji placeholder - admin dapat mengganti dengan foto asli */
  emoji: string;
  deskripsi: string;
}

export const FOOD_CATEGORIES: { key: FoodCategory; label: string; emoji: string; color: string }[] = [
  { key: "makanan-pokok", label: "Makanan Pokok", emoji: "🍚", color: "bg-amber-100 text-amber-800" },
  { key: "lauk-hewani", label: "Lauk Hewani", emoji: "🐟", color: "bg-rose-100 text-rose-800" },
  { key: "lauk-nabati", label: "Lauk Nabati", emoji: "🫘", color: "bg-orange-100 text-orange-800" },
  { key: "sayuran", label: "Sayuran", emoji: "🥬", color: "bg-green-100 text-green-800" },
  { key: "buah", label: "Buah", emoji: "🍎", color: "bg-pink-100 text-pink-800" },
  { key: "minyak-lemak", label: "Minyak & Lemak", emoji: "🫒", color: "bg-yellow-100 text-yellow-800" },
  { key: "camilan", label: "Camilan Sehat", emoji: "🍪", color: "bg-purple-100 text-purple-800" },
];

export const FOODS: FoodItem[] = [
  // Makanan Pokok
  {
    id: "nasi-putih",
    nama: "Nasi Putih",
    kategori: "makanan-pokok",
    urt: "1 centong (100 g)",
    beratGram: 100,
    energiKkal: 175,
    proteinG: 2.7,
    lemakG: 0.2,
    karbohidratG: 40.0,
    emoji: "🍚",
    deskripsi: "Sumber karbohidrat utama, mudah dicerna.",
  },
  {
    id: "nasi-merah",
    nama: "Nasi Merah",
    kategori: "makanan-pokok",
    urt: "1 centong (100 g)",
    beratGram: 100,
    energiKkal: 165,
    proteinG: 3.2,
    lemakG: 0.5,
    karbohidratG: 35.0,
    emoji: "🍚",
    deskripsi: "Lebih tinggi serat daripada nasi putih.",
  },
  {
    id: "kentang-rebus",
    nama: "Kentang Rebus",
    kategori: "makanan-pokok",
    urt: "1 biji sedang (110 g)",
    beratGram: 110,
    energiKkal: 87,
    proteinG: 2.0,
    lemakG: 0.1,
    karbohidratG: 20.0,
    emoji: "🥔",
    deskripsi: "Sumber karbohidrat dengan vitamin C.",
  },
  {
    id: "ubi-rebus",
    nama: "Ubi Rebus",
    kategori: "makanan-pokok",
    urt: "1 biji sedang (100 g)",
    beratGram: 100,
    energiKkal: 86,
    proteinG: 1.6,
    lemakG: 0.1,
    karbohidratG: 20.0,
    emoji: "🍠",
    deskripsi: "Kaya beta-karoten, baik untuk penglihatan.",
  },
  {
    id: "jagung-rebus",
    nama: "Jagung Rebus",
    kategori: "makanan-pokok",
    urt: "1 biji sedang (100 g)",
    beratGram: 100,
    energiKkal: 86,
    proteinG: 3.2,
    lemakG: 1.2,
    karbohidratG: 19.0,
    emoji: "🌽",
    deskripsi: "Sumber karbohidrat dan serat.",
  },
  {
    id: "roti-putih",
    nama: "Roti Tawar",
    kategori: "makanan-pokok",
    urt: "1 lembar (30 g)",
    beratGram: 30,
    energiKkal: 79,
    proteinG: 2.6,
    lemakG: 1.0,
    karbohidratG: 14.5,
    emoji: "🍞",
    deskripsi: "Praktis untuk sarapan.",
  },
  {
    id: "bubur-beras",
    nama: "Bubur Beras",
    kategori: "makanan-pokok",
    urt: "1 mangkok kecil (150 g)",
    beratGram: 150,
    energiKkal: 78,
    proteinG: 1.5,
    lemakG: 0.2,
    karbohidratG: 17.0,
    emoji: "🍚",
    deskripsi: "Tekstur lembut, cocok untuk MP-ASI awal.",
  },
  {
    id: "mie-pasta",
    nama: "Mie/Pasta Rebus",
    kategori: "makanan-pokok",
    urt: "1 mangkok (100 g)",
    beratGram: 100,
    energiKkal: 138,
    proteinG: 5.0,
    lemakG: 0.5,
    karbohidratG: 27.0,
    emoji: "🍜",
    deskripsi: "Sumber karbohidrat alternatif.",
  },

  // Lauk Hewani
  {
    id: "telur-ayam-rebus",
    nama: "Telur Ayam Rebus",
    kategori: "lauk-hewani",
    urt: "1 butir (55 g)",
    beratGram: 55,
    energiKkal: 86,
    proteinG: 7.0,
    lemakG: 6.0,
    karbohidratG: 0.6,
    emoji: "🥚",
    deskripsi: "Protein hewani lengkap, murah, mudah didapat.",
  },
  {
    id: "daging-ayam",
    nama: "Daging Ayam Rebus",
    kategori: "lauk-hewani",
    urt: "1 potong sedang (40 g)",
    beratGram: 40,
    energiKkal: 66,
    proteinG: 8.8,
    lemakG: 3.0,
    karbohidratG: 0.0,
    emoji: "🍗",
    deskripsi: "Protein hewani tinggi, rendah lemak (bagian dada).",
  },
  {
    id: "daging-sapi",
    nama: "Daging Sapi Rebus",
    kategori: "lauk-hewani",
    urt: "1 potong sedang (40 g)",
    beratGram: 40,
    energiKkal: 84,
    proteinG: 8.4,
    lemakG: 5.2,
    karbohidratG: 0.0,
    emoji: "🥩",
    deskripsi: "Tinggi zat besi dan protein.",
  },
  {
    id: "ikan-lele",
    nama: "Ikan Lele Rebus",
    kategori: "lauk-hewani",
    urt: "1 potong sedang (50 g)",
    beratGram: 50,
    energiKkal: 70,
    proteinG: 9.0,
    lemakG: 3.0,
    karbohidratG: 0.0,
    emoji: "🐟",
    deskripsi: "Protein hewani ekonomis.",
  },
  {
    id: "ikan-tongkol",
    nama: "Ikan Tongkol Rebus",
    kategori: "lauk-hewani",
    urt: "1 potong sedang (50 g)",
    beratGram: 50,
    energiKkal: 56,
    proteinG: 11.5,
    lemakG: 0.5,
    karbohidratG: 0.0,
    emoji: "🐟",
    deskripsi: "Tinggi protein, asam lemak omega-3.",
  },
  {
    id: "udang-rebus",
    nama: "Udang Rebus",
    kategori: "lauk-hewani",
    urt: "5 ekor kecil (30 g)",
    beratGram: 30,
    energiKkal: 30,
    proteinG: 6.5,
    lemakG: 0.3,
    karbohidratG: 0.0,
    emoji: "🦐",
    deskripsi: "Tinggi protein, rendah lemak.",
  },
  {
    id: "hati-ayam",
    nama: "Hati Ayam Rebus",
    kategori: "lauk-hewani",
    urt: "1 potong kecil (30 g)",
    beratGram: 30,
    energiKkal: 39,
    proteinG: 6.0,
    lemakG: 1.3,
    karbohidratG: 0.4,
    emoji: "🍖",
    deskripsi: "Sangat tinggi zat besi, baik untuk cegah anemia.",
  },
  {
    id: "tempe-ikan",
    nama: "Bakso Ikan",
    kategori: "lauk-hewani",
    urt: "3 butir kecil (30 g)",
    beratGram: 30,
    energiKkal: 36,
    proteinG: 5.0,
    lemakG: 1.0,
    karbohidratG: 1.5,
    emoji: "🍡",
    deskripsi: "Disukai anak-anak, tinggi protein.",
  },
  {
    id: "susu-sapi",
    nama: "Susu Sapi (Full Cream)",
    kategori: "lauk-hewani",
    urt: "1 gelas (200 ml)",
    beratGram: 200,
    energiKkal: 122,
    proteinG: 6.6,
    lemakG: 6.6,
    karbohidratG: 9.4,
    emoji: "🥛",
    deskripsi: "Sumber kalsium dan protein.",
  },
  {
    id: "yogurt",
    nama: "Yogurt Plain",
    kategori: "lauk-hewani",
    urt: "1 cup kecil (100 g)",
    beratGram: 100,
    energiKkal: 61,
    proteinG: 3.5,
    lemakG: 3.3,
    karbohidratG: 4.7,
    emoji: "🥛",
    deskripsi: "Probiotik untuk pencernaan sehat.",
  },

  // Lauk Nabati
  {
    id: "tempe",
    nama: "Tempe Rebus/Goreng",
    kategori: "lauk-nabati",
    urt: "1 potong sedang (50 g)",
    beratGram: 50,
    energiKkal: 94,
    proteinG: 9.3,
    lemakG: 4.5,
    karbohidratG: 4.7,
    emoji: "🫘",
    deskripsi: "Protein nabati ekonomis, tinggi serat.",
  },
  {
    id: "tahu",
    nama: "Tahu Rebus/Goreng",
    kategori: "lauk-nabati",
    urt: "1 potong sedang (50 g)",
    beratGram: 50,
    energiKkal: 41,
    proteinG: 4.0,
    lemakG: 2.0,
    karbohidratG: 1.5,
    emoji: "⬜",
    deskripsi: "Protein nabati, mudah dicerna.",
  },
  {
    id: "kacang-hijau",
    nama: "Kacang Hijau Rebus",
    kategori: "lauk-nabati",
    urt: "3 sendok makan (45 g)",
    beratGram: 45,
    energiKkal: 56,
    proteinG: 4.0,
    lemakG: 0.2,
    karbohidratG: 10.0,
    emoji: "🫛",
    deskripsi: "Tinggi protein, serat, dan zat besi.",
  },
  {
    id: "kacang-merah",
    nama: "Kacang Merah Rebus",
    kategori: "lauk-nabati",
    urt: "2 sendok makan (30 g)",
    beratGram: 30,
    energiKkal: 40,
    proteinG: 2.5,
    lemakG: 0.1,
    karbohidratG: 7.0,
    emoji: "🫘",
    deskripsi: "Sumber serat dan protein nabati.",
  },
  {
    id: "edamame",
    nama: "Edamame Rebus",
    kategori: "lauk-nabati",
    urt: "3 sendok makan (45 g)",
    beratGram: 45,
    energiKkal: 60,
    proteinG: 5.4,
    lemakG: 2.5,
    karbohidratG: 4.7,
    emoji: "🫛",
    deskripsi: "Protein nabati tinggi, disukai anak-anak.",
  },

  // Sayuran
  {
    id: "bayam",
    nama: "Bayam Rebus",
    kategori: "sayuran",
    urt: "1 mangkok kecil (50 g)",
    beratGram: 50,
    energiKkal: 12,
    proteinG: 1.4,
    lemakG: 0.2,
    karbohidratG: 2.0,
    emoji: "🥬",
    deskripsi: "Tinggi zat besi dan vitamin A.",
  },
  {
    id: "wortel",
    nama: "Wortel Rebus",
    kategori: "sayuran",
    urt: "1 batang sedang (50 g)",
    beratGram: 50,
    energiKkal: 17,
    proteinG: 0.4,
    lemakG: 0.1,
    karbohidratG: 4.0,
    emoji: "🥕",
    deskripsi: "Sumber beta-karoten untuk mata.",
  },
  {
    id: "brokoli",
    nama: "Brokoli Rebus",
    kategori: "sayuran",
    urt: "3-4 kuntum kecil (50 g)",
    beratGram: 50,
    energiKkal: 17,
    proteinG: 1.4,
    lemakG: 0.2,
    karbohidratG: 3.3,
    emoji: "🥦",
    deskripsi: "Tinggi vitamin C dan serat.",
  },
  {
    id: "tomat",
    nama: "Tomat Segar",
    kategori: "sayuran",
    urt: "1 buah sedang (50 g)",
    beratGram: 50,
    energiKkal: 9,
    proteinG: 0.4,
    lemakG: 0.1,
    karbohidratG: 2.0,
    emoji: "🍅",
    deskripsi: "Sumber vitamin C dan likopen.",
  },
  {
    id: "buncis",
    nama: "Buncis Rebus",
    kategori: "sayuran",
    urt: "5-7 batang (50 g)",
    beratGram: 50,
    energiKkal: 16,
    proteinG: 0.9,
    lemakG: 0.1,
    karbohidratG: 3.5,
    emoji: "🫛",
    deskripsi: "Serat tinggi, mudah dicerna.",
  },
  {
    id: "labu-kuning",
    nama: "Labu Kuning Rebus",
    kategori: "sayuran",
    urt: "1 potong sedang (80 g)",
    beratGram: 80,
    energiKkal: 21,
    proteinG: 0.6,
    lemakG: 0.1,
    karbohidratG: 5.0,
    emoji: "🎃",
    deskripsi: "Kaya vitamin A, manis alami.",
  },
  {
    id: "sawi",
    nama: "Sawi Rebus",
    kategori: "sayuran",
    urt: "1 mangkok kecil (50 g)",
    beratGram: 50,
    energiKkal: 7,
    proteinG: 0.6,
    lemakG: 0.1,
    karbohidratG: 1.2,
    emoji: "🥬",
    deskripsi: "Sumber kalsium dan serat.",
  },
  {
    id: "kangkung",
    nama: "Kangkung Rebus",
    kategori: "sayuran",
    urt: "1 mangkok kecil (50 g)",
    beratGram: 50,
    energiKkal: 14,
    proteinG: 1.4,
    lemakG: 0.2,
    karbohidratG: 2.3,
    emoji: "🥬",
    deskripsi: "Ekonomis, kaya zat besi.",
  },

  // Buah
  {
    id: "pisang",
    nama: "Pisang",
    kategori: "buah",
    urt: "1 buah sedang (100 g)",
    beratGram: 100,
    energiKkal: 89,
    proteinG: 1.1,
    lemakG: 0.3,
    karbohidratG: 22.8,
    emoji: "🍌",
    deskripsi: "Praktis, tinggi kalium.",
  },
  {
    id: "apel",
    nama: "Apel",
    kategori: "buah",
    urt: "1 buah sedang (150 g)",
    beratGram: 150,
    energiKkal: 78,
    proteinG: 0.4,
    lemakG: 0.5,
    karbohidratG: 20.7,
    emoji: "🍎",
    deskripsi: "Serat tinggi, baik untuk pencernaan.",
  },
  {
    id: "pepaya",
    nama: "Pepaya",
    kategori: "buah",
    urt: "1 iris sedang (100 g)",
    beratGram: 100,
    energiKkal: 43,
    proteinG: 0.5,
    lemakG: 0.3,
    karbohidratG: 10.8,
    emoji: "🫓",
    deskripsi: "Membantu pencernaan, kaya vitamin A.",
  },
  {
    id: "jeruk",
    nama: "Jeruk Manis",
    kategori: "buah",
    urt: "1 buah sedang (130 g)",
    beratGram: 130,
    energiKkal: 47,
    proteinG: 0.9,
    lemakG: 0.1,
    karbohidratG: 11.8,
    emoji: "🍊",
    deskripsi: "Tinggi vitamin C.",
  },
  {
    id: "mangga",
    nama: "Mangga",
    kategori: "buah",
    urt: "1 iris sedang (100 g)",
    beratGram: 100,
    energiKkal: 60,
    proteinG: 0.8,
    lemakG: 0.4,
    karbohidratG: 15.0,
    emoji: "🥭",
    deskripsi: "Kaya beta-karoten.",
  },
  {
    id: "semangka",
    nama: "Semangka",
    kategori: "buah",
    urt: "1 iris besar (150 g)",
    beratGram: 150,
    energiKkal: 46,
    proteinG: 0.9,
    lemakG: 0.2,
    karbohidratG: 11.5,
    emoji: "🍉",
    deskripsi: "Segar, membantu hidrasi.",
  },
  {
    id: "alpukat",
    nama: "Alpukat",
    kategori: "buah",
    urt: "1/2 buah sedang (80 g)",
    beratGram: 80,
    energiKkal: 128,
    proteinG: 1.6,
    lemakG: 11.8,
    karbohidratG: 4.2,
    emoji: "🥑",
    deskripsi: "Lemak sehat untuk otak anak.",
  },
  {
    id: "melon",
    nama: "Melon",
    kategori: "buah",
    urt: "1 iris sedang (100 g)",
    beratGram: 100,
    energiKkal: 34,
    proteinG: 0.8,
    lemakG: 0.2,
    karbohidratG: 8.0,
    emoji: "🍈",
    deskripsi: "Sumber vitamin C dan air.",
  },

  // Minyak & Lemak
  {
    id: "minyak-kelapa",
    nama: "Minyak Kelapa Sawit",
    kategori: "minyak-lemak",
    urt: "1 sendok teh (5 g)",
    beratGram: 5,
    energiKkal: 45,
    proteinG: 0.0,
    lemakG: 5.0,
    karbohidratG: 0.0,
    emoji: "🫗",
    deskripsi: "Tambah kalori untuk anak, gunakan secukupnya.",
  },
  {
    id: "minyak-zaitun",
    nama: "Minyak Zaitun Extra Virgin",
    kategori: "minyak-lemak",
    urt: "1 sendok teh (5 g)",
    beratGram: 5,
    energiKkal: 44,
    proteinG: 0.0,
    lemakG: 5.0,
    karbohidratG: 0.0,
    emoji: "🫒",
    deskripsi: "Lemak tak jenuh, baik untuk kesehatan.",
  },
  {
    id: "mentega",
    nama: "Mentega",
    kategori: "minyak-lemak",
    urt: "1 sendok teh (5 g)",
    beratGram: 5,
    energiKkal: 36,
    proteinG: 0.1,
    lemakG: 4.0,
    karbohidratG: 0.0,
    emoji: "🧈",
    deskripsi: "Sumber lemak untuk otak.",
  },
  {
    id: "kelapa-parut",
    nama: "Kelapa Parut",
    kategori: "minyak-lemak",
    urt: "1 sendok makan (10 g)",
    beratGram: 10,
    energiKkal: 66,
    proteinG: 0.7,
    lemakG: 6.4,
    karbohidratG: 2.2,
    emoji: "🥥",
    deskripsi: "Tambahkan pada makanan untuk ekstra kalori.",
  },

  // Camilan Sehat
  {
    id: "pisang-goreng",
    nama: "Pisang Goreng (1 biji)",
    kategori: "camilan",
    urt: "1 biji (60 g)",
    beratGram: 60,
    energiKkal: 145,
    proteinG: 1.4,
    lemakG: 6.5,
    karbohidratG: 21.0,
    emoji: "🍌",
    deskripsi: "Camilan favorit, batasi porsi.",
  },
  {
    id: "roti-gandum",
    nama: "Roti Gandum dengan Selai Kacang",
    kategori: "camilan",
    urt: "1 lembar (40 g)",
    beratGram: 40,
    energiKkal: 145,
    proteinG: 5.5,
    lemakG: 6.0,
    karbohidratG: 17.5,
    emoji: "🍞",
    deskripsi: "Camilan padat gizi.",
  },
  {
    id: "puding-susu",
    nama: "Puding Susu",
    kategori: "camilan",
    urt: "1 cup kecil (100 g)",
    beratGram: 100,
    energiKkal: 80,
    proteinG: 3.0,
    lemakG: 2.0,
    karbohidratG: 12.0,
    emoji: "🍮",
    deskripsi: "Camilan lembut tinggi kalsium.",
  },
  {
    id: "bubur-kacang-hijau",
    nama: "Bubur Kacang Hijau",
    kategori: "camilan",
    urt: "1 mangkok kecil (150 g)",
    beratGram: 150,
    energiKkal: 175,
    proteinG: 6.5,
    lemakG: 0.7,
    karbohidratG: 35.0,
    emoji: "🥣",
    deskripsi: "Camilan tradisional bergizi.",
  },
  {
    id: "pisang-susu",
    nama: "Smoothie Pisang-Susu",
    kategori: "camilan",
    urt: "1 gelas (200 ml)",
    beratGram: 200,
    energiKkal: 130,
    proteinG: 5.0,
    lemakG: 3.0,
    karbohidratG: 21.0,
    emoji: "🥤",
    deskripsi: "Minuman padat gizi untuk anak.",
  },
  {
    id: "kacang-rebus",
    nama: "Kacang Tanah Rebus",
    kategori: "camilan",
    urt: "1 genggam (20 g)",
    beratGram: 20,
    energiKkal: 56,
    proteinG: 2.6,
    lemakG: 4.8,
    karbohidratG: 1.6,
    emoji: "🥜",
    deskripsi: "Camilan tinggi protein.",
  },
];
